### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "emailteste02@gmail.com",
    "password": "test",
    "roles": ["admin"]
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "emailteste02@gmail.com",
    "password": "test"
}

### refresh
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVtYWlsdGVzdGUwMkBnbWFpbC5jb20iLCJzdWIiOiI4YThiMzk2YS0xMjZkLTQ0NzItYmZhMi0xZDc1YmQyMWM3MDMiLCJyb2xlcyI6WyJhZG1pbiJdLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzYwNjIzMjAxLCJleHAiOjE3NjA2MjMyNjF9.hLLGyAUmlluGyjnf-BBcvmKXD8MOrV_tnL4oRa5gHHw"
}