### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "emailteste02@gmail.com",
    "password": "test"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "emailteste02@gmail.com",
    "password": "test"
}